### POST requisição para rota de criação de comentário
POST http://localhost:8080/comment
Content-Type: application/json

{
  "message": "teste",
  "post_id": 1
}

### PUT requisição para rota de atualização comentário pelo id
PUT http://localhost:8080/comment/3
Content-Type: application/json

{
  "message": "teste"
}

### GET requisição para rota de comments para listar todos os comentários
GET http://localhost:8080/comment
Accept: application/json

### GET requisição para rota de listar comentário pelo id
GET http://localhost:8080/comment/1
Accept: application/json

### DELETE requisição para rota para excluir comentários
DELETE http://localhost:8080/comment/1
Content-Type: application/json