### GET requisição para a rota de users para listar todos os usuários
GET http://localhost:3000/users
Accept: application/json

### GET requisição para rota de posts para listar todas as postagens
GET http://localhost:3000/posts
Accept: application/json